spring:
  datasource:
    hikari:
      maximum-pool-size: 4
    password: postgres
    url: jdbc:postgresql://localhost:5432/spring
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update